Metrics/LineLength:
        Max: 110
Metrics/AbcSize:
        Max: 36

Metrics/MethodLength:
        Max: 20

Style/PredicateName:
        # should still be accepted
        NameWhitelist:
                - is_ugly
