# Site settings
title: Arthur
email: arthur4it@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        Arthur's solution
baseurl: "/LeetCodePractice" # the subpath of your site, e.g. /blog/
url: "http://accearth.github.io" # the base hostname & protocol for your site
github_username:  acearth

# Build settings
markdown: rdiscount

permalink: /:year/:month/:day/:title.html
